// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Timer$ReactHooksTemplate = require("./Timer.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Timer$ReactHooksTemplate.make, { }), "root");

/*  Not a pure module */
